# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "fruitful-infrastructure-app"
client_id = "dcabaa63afe82e18e89412ecc81b67e3"
application_url = "https://b192-111-92-116-35.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,unauthenticated_read_customers,read_inventory"

[auth]
redirect_urls = [
  "https://b192-111-92-116-35.ngrok-free.app/auth/callback",
  "https://b192-111-92-116-35.ngrok-free.app/auth/shopify/callback",
  "https://b192-111-92-116-35.ngrok-free.app/api/auth/callback",
  "https://b192-111-92-116-35.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sha7hid.myshopify.com"
